version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: nl2sparql-prometheus
    working_dir: /etc/prometheus
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --config.expand-env
    environment:
      - PROMETHEUS_BEARER_TOKEN=${API_AUTH_TOKEN}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: nl2sparql-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    ports:
      - "3000:3000"
    restart: unless-stopped
