name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FUSEKI_BASE_URL: http://example.org
      FUSEKI_DATASET: test
      FUSEKI_USER: user
      FUSEKI_PASSWORD: pass
      OPENAI_API_KEY: sk-ci
      LLM_MODEL: gpt-4.1-mini
      LLM_TEMPERATURE: "0.2"
      LLM_MAX_OUTPUT_TOKENS: "1200"
      CHANGES_GRAPH: urn:ci:changes
      API_AUTH_TOKEN: ci-token
      RATE_LIMIT_PER_MINUTE: "120"
      RATE_LIMIT_BURST: "30"
      ENABLE_PROMETHEUS_METRICS: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Build UI
        working-directory: ui
        run: |
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: pytest -q
